// lib/queries/orders.ts
// Server-side data fetching for orders (API routes + RSC)

import { createServerSupabaseClient } from "@/lib/supabase/server";
import { supabaseAdmin } from "@/lib/supabase/admin";
import type {
  Order,
  OrderWithItems,
  OrderInsert,
  OrderItemInsert,
} from "@/types/database";

/**
 * Fetch orders for a customer (server component).
 */
export async function getOrdersByCustomer(
  customerId: string,
): Promise<Order[]> {
  const supabase = await createServerSupabaseClient();

  const { data, error } = await supabase
    .from("orders")
    .select("*")
    .eq("customer_id", customerId)
    .order("created_at", { ascending: false });

  if (error) throw error;
  return (data as Order[]) ?? [];
}

/**
 * Fetch a single order with items (server component).
 */
export async function getOrderById(
  orderId: string,
): Promise<OrderWithItems | null> {
  const supabase = await createServerSupabaseClient();

  const { data, error } = await supabase
    .from("orders")
    .select("*, order_items(*)")
    .eq("id", orderId)
    .single();

  if (error) {
    if (error.code === "PGRST116") return null;
    throw error;
  }

  return data as unknown as OrderWithItems;
}

/**
 * Create a new order with items.
 * Uses the admin client to bypass RLS.
 * Called from the API route handler.
 */
export async function createOrder(
  orderData: Omit<OrderInsert, "order_number">,
  items: Omit<OrderItemInsert, "order_id">[],
): Promise<OrderWithItems> {
  // 1. Insert the order (order_number auto-generated by trigger)
  const { data: order, error: orderError } = await supabaseAdmin
    .from("orders")
    .insert({
      ...orderData,
      order_number: "", // Will be overwritten by trigger
      status_history: [
        {
          status: "pending",
          timestamp: new Date().toISOString(),
          by: "system",
          note: "Order placed",
        },
      ],
    })
    .select()
    .single();

  if (orderError) throw orderError;

  // 2. Insert all order items linked to the order
  const itemsWithOrderId = items.map((item) => ({
    ...item,
    order_id: order.id,
  }));

  const { data: orderItems, error: itemsError } = await supabaseAdmin
    .from("order_items")
    .insert(itemsWithOrderId)
    .select();

  if (itemsError) {
    // Rollback: delete the order if items fail
    await supabaseAdmin.from("orders").delete().eq("id", order.id);
    throw itemsError;
  }

  return {
    ...(order as unknown as OrderWithItems),
    order_items: orderItems as unknown as OrderWithItems["order_items"],
  };
}

/**
 * Update order status with history tracking.
 * Uses admin client — called from API route.
 */
export async function updateOrderStatus(
  orderId: string,
  newStatus: string,
  updatedBy: string = "admin",
  note?: string,
): Promise<Order> {
  // Fetch current order to append to status_history
  const { data: currentOrder, error: fetchErr } = await supabaseAdmin
    .from("orders")
    .select("status_history")
    .eq("id", orderId)
    .single();

  if (fetchErr) throw fetchErr;

  const currentHistory = Array.isArray(currentOrder?.status_history)
    ? currentOrder.status_history
    : [];

  const updatedHistory = [
    ...currentHistory,
    {
      status: newStatus,
      timestamp: new Date().toISOString(),
      by: updatedBy,
      note: note || `Status changed to ${newStatus}`,
    },
  ];

  const { data, error } = await supabaseAdmin
    .from("orders")
    .update({
      status: newStatus,
      status_history: updatedHistory,
    })
    .eq("id", orderId)
    .select()
    .single();

  if (error) throw error;
  return data as unknown as Order;
}

/**
 * Fetch all orders for CMS (admin view).
 * Uses admin client — no RLS restrictions.
 */
export async function getAllOrders(options?: {
  status?: string;
  limit?: number;
  offset?: number;
}): Promise<Order[]> {
  let query = supabaseAdmin
    .from("orders")
    .select("*")
    .order("created_at", { ascending: false });

  if (options?.status) {
    query = query.eq("status", options.status);
  }

  if (options?.limit) {
    query = query.limit(options.limit);
  }

  if (options?.offset) {
    query = query.range(
      options.offset,
      options.offset + (options.limit || 50) - 1,
    );
  }

  const { data, error } = await query;

  if (error) throw error;
  return (data as unknown as Order[]) ?? [];
}
