import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { z } from "zod";

const orderItemSchema = z.object({
  product_id: z.string().uuid().optional().nullable(),
  product_name: z.string(),
  product_slug: z.string().optional().nullable(),
  product_image: z.string().optional().nullable(),
  category: z.string().optional().nullable(),
  unit_price: z.number(),
  quantity: z.number(),
  line_total: z.number(),
  selected_options: z.record(z.any()).optional().nullable(),
  design_file_url: z.string().optional().nullable(),
  design_file_name: z.string().optional().nullable(),
  design_file_size: z.number().optional().nullable(),
});

const createOrderSchema = z.object({
  customer_name: z.string(),
  customer_email: z.string().email(),
  customer_phone: z.string().optional().nullable(),
  customer_tin: z.string().optional().nullable(),
  delivery_address: z.string().optional().nullable(),
  delivery_city: z.string().optional().nullable(),
  delivery_sub_city: z.string().optional().nullable(),
  status: z.string().default("pending"),
  subtotal: z.number(),
  delivery_fee: z.number().default(0),
  tax_amount: z.number().default(0),
  total_amount: z.number(),
  currency: z.string().default("ETB"),
  special_instructions: z.string().optional().nullable(),
  terms_accepted: z
    .boolean()
    .refine((val) => val === true, "Must accept terms"),
  payment_method: z.string().optional().nullable(),
  items: z.array(orderItemSchema).min(1),
});

export async function POST(req: Request) {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    const user = session?.user;

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await req.json();
    const validatedData = createOrderSchema.parse(body);

    const { data: customerProfile } = await supabaseAdmin
      .from("customer_profiles")
      .select("id")
      .eq("auth_user_id", user.id)
      .single();

    const { data: order, error: orderError } = await supabaseAdmin
      .from("orders")
      .insert({
        customer_id: customerProfile?.id || null, // Will be null if guest, but we enforced auth above
        order_number: "", // Generated by DB trigger, added for TS satisfaction
        customer_name: validatedData.customer_name,
        customer_email: validatedData.customer_email,
        customer_phone: validatedData.customer_phone,
        customer_tin: validatedData.customer_tin,
        delivery_address: validatedData.delivery_address,
        delivery_city: validatedData.delivery_city,
        delivery_sub_city: validatedData.delivery_sub_city,
        status: validatedData.status,
        subtotal: validatedData.subtotal,
        delivery_fee: validatedData.delivery_fee,
        tax_amount: validatedData.tax_amount,
        total_amount: validatedData.total_amount,
        currency: validatedData.currency,
        special_instructions: validatedData.special_instructions,
        terms_accepted: validatedData.terms_accepted,
        terms_accepted_at: new Date().toISOString(),
        payment_method: validatedData.payment_method,
        status_history: [
          {
            status: "pending",
            timestamp: new Date().toISOString(),
            note: "Order placed",
          },
        ],
      })
      .select()
      .single();

    if (orderError || !order) {
      console.error("Order creation failed", orderError);
      return NextResponse.json(
        { error: "Failed to create order" },
        { status: 500 },
      );
    }

    const itemsToInsert = validatedData.items.map((item) => ({
      order_id: order.id,
      product_id: item.product_id,
      product_name: item.product_name,
      product_slug: item.product_slug,
      product_image: item.product_image,
      category: item.category,
      unit_price: item.unit_price,
      quantity: item.quantity,
      line_total: item.line_total,
      selected_options: item.selected_options,
      design_file_url: item.design_file_url,
      design_file_name: item.design_file_name,
      design_file_size: item.design_file_size,
    }));

    const { error: itemsError } = await supabaseAdmin
      .from("order_items")
      .insert(itemsToInsert);

    if (itemsError) {
      console.error("Order items creation failed", itemsError);
      return NextResponse.json(
        { error: "Failed to create order items" },
        { status: 500 },
      );
    }

    return NextResponse.json({ success: true, order }, { status: 201 });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: "Validation failed", details: error.errors },
        { status: 400 },
      );
    }
    console.error("POST /api/orders error", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}

export async function GET() {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    const user = session?.user;

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const { data: customerProfile } = await supabaseAdmin
      .from("customer_profiles")
      .select("id")
      .eq("auth_user_id", user.id)
      .single();

    if (!customerProfile) {
      return NextResponse.json({ orders: [] }, { status: 200 });
    }

    const { data: orders, error } = await supabaseAdmin
      .from("orders")
      .select(
        "id, order_number, created_at, status, total_amount, payment_status",
      )
      .eq("customer_id", customerProfile.id)
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Orders fetch error", error);
      return NextResponse.json(
        { error: "Failed to fetch orders" },
        { status: 500 },
      );
    }

    return NextResponse.json({ orders }, { status: 200 });
  } catch (error) {
    console.error("GET /api/orders error", error);
    return NextResponse.json(
      { error: "Internal Server Error" },
      { status: 500 },
    );
  }
}
